### ISSUE TITLE
CLI boilerplate

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/node-module-boilerplate#1]
Mostly note to self. Need to add a boilerplate for how I do command-line apps too. And implement a prompt in the Yeoman generator.

**Comment by arthurvr** [comment]
FYI, https://github.com/sindresorhus/generator-nm/compare/master...arthurvr:cli?expand=1. Had that one locally for a while. Built that for my personal needs but I guess it pretty much matches your preferences.

**Comment by sindresorhus** [comment]
@arthurvr Looks good. Can you open a PR? :)

**Comment by arthurvr** [comment]
done
