### ISSUE TITLE
Boil the plate!

### ISSUE THREAD

**Issue by bzurkowski** [sindresorhus/node-module-boilerplate#25]
Some time ago I created a Python tool ([Boil](https://github.com/bzurkowski/boil)) for bootstraping projects in various technologies (languages, frameworks).

First, you search for available (boiler)plates:

```
➜  $ boil list
Available plates:
ansible_role            license                 python_script
bash_script             python_package          ruby_gem

➜  $ boil search python
Found plates (2):
python_package          python_script
```

Then, fill in some variables:

```
➜  $ boil new python_package
Initializing new Python package.
Package name [e.g. fancy_package]:
fancy_package
Description [e.g. Super fancy package]:
Some fancy stuff
Url [e.g. https://github.com/username/package_name]:
https://github.com/bzurkowski/fancy_package
License [MIT]:
Apache License 2.0
Author [e.g. John Smith]:
Just me
Done!
```

You get complete package structure with proper module names, basic test environment, linter, exception class etc.:

```
➜ $ tree fancy_package
fancy_package
├── MANIFEST.in
├── README.md
├── README.rst
├── fancy_package
│   ├── __init__.py
│   └── exceptions.py
├── requirements.txt
├── setup.py
├── test-requirements.txt
├── tests
│   ├── integration
│   │   ├── __init__.py
│   │   └── test_example.py
│   └── unit
│       ├── __init__.py
│       └── test_example.py
└── tox.ini
```

The tool is based on Jinja templates like [this one](https://github.com/bzurkowski/boil/tree/master/boil/plates/python_package/templates/%7B%7B%20package_name%20%7D%7D).

I wonder if I could use your code as a plate in my project. With Node.js support it could help you too! 😉

**Comment by sindresorhus** [comment]
Nice work. While it's not something I would personally use, feel free to use the boilerplate contents here as you please.
