### ISSUE TITLE
Remove `sudo: false` from `.travis.yml` templates?

### ISSUE THREAD

**Issue by alrra** [sindresorhus/node-module-boilerplate#6]
@sindresorhus Since the template code will most probably end up in newly created repositories, there is no need to include `sudo: false` in the `.travis.yml` file, as that is now the default:

> The default behavior, when no sudo usage is detected in any customizable build phases, depends on the date when the repository is first recognized by Travis CI:
>
>    * For repos we recognize before 2015-01-01, linux builds are sent to our standard infrastructure.
>    * __For repos we recognize on or after 2015-01-01, linux builds are sent to our container-based infrastructure__

From: http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure

**Comment by arthurvr** [comment]
Awesome. Thanks @alrra!
